accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import CreateUserView


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", CreateUserView.as_view(), name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url="/receipts/")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCreateView,
    AccountCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="categories_list",
    ),
    path(
        "accounts/",
        AccountListView.as_view(),
        name="accounts_list",
    ),
    path(
        "categories/create/",
        ExpenseCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="create_account",
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, on_delete=models.CASCADE, related_name="categories"
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, on_delete=models.CASCADE, related_name="accounts"
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL, on_delete=models.CASCADE, related_name="receipts"
    )
    category = models.ForeignKey(
        "ExpenseCategory", on_delete=models.CASCADE, related_name="receipts"
    )
    account = models.ForeignKey(
        "Account", on_delete=models.CASCADE, related_name="receipts", null=True
    )

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

# Create your views here.
class CreateUserView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("home")
    template_name = "registration/signup.html"

receipts/views.py
from django.views.generic.list import ListView
from django.shortcuts import redirect, render
from receipts.models import Receipt, ExpenseCategory, Account
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/new.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        form.instance.purchaser = self.request.user
        form.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/categorylist.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accountlist.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/newexpense.html"
    fields = ["name"]

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.save()
        return redirect("categories_list")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/newaccount.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.save()
        return redirect("accounts_list")

receipts/templates/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>django_two_shot</title>
  </head>
  <nav>
    <ul>
      {% if user.is_authenticated %}
      <li><a href="{% url 'logout' %}">logout</a></li>
      {% endif %} {% if not user.is_authenticated %}
      <li><a href="{% url 'signup' %}">signup</a></li>
      {% endif %} {% if not user.is_authenticated %}
      <li><a href="{% url 'login' %}">login</a></li>
      {% endif %}
      <li><a href="{% url 'create_receipt' %}">create receipt</a></li>
      <li><a href="{% url 'create_category' %}">create create_category</a></li>
    </ul>
  </nav>
  <body>
    {%block content%} {% endblock content %}
  </body>
</html>

receipts/templates/receipts/accountlist.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <table>
      <thead>
        <th>Name</th>
        <th>Number</th>
        <th>Number of receipts</th>
      </thead>
      <tbody>
        {% for account in account_list %}
        <tr>
          <td>{{account.name}}</td>
          <td>{{account.number}}</td>
          <td>{{account.receipts.all|length}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock content %}

receipts/templates/receipts/categorylist.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <table>
      <thead>
        <th>Name</th>
        <th>Number of receipts</th>
      </thead>
      <tbody>
        {% for expense in expensecategory_list %}
        <tr>
          <td>{{expense.name}}</td>
          <td>{{expense.receipts.all|length}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %} {% block content %}
<main>
  <h1>My Receipts</h1>
  <table>
    <thead>
      <th>Vendor</th>
      <th>Total</th>
      <th>Tax</th>
      <th>Date</th>
      <th>Category</th>
      <th>Account</th>
    </thead>
    <tbody>
      {% for receipt in receipt_list %}
      <tr>
        <td>{{receipt.vendor}}</td>
        <td>{{receipt.total}}</td>
        <td>{{receipt.tax}}</td>
        <td>{{receipt.date|date:"n/j/y"}}</td>
        <td>{{receipt.category}}</td>
        <td>{{receipt.account}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>

{% endblock content %}

receipts/templates/receipts/new.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <h1>Create Receipt</h1>
    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <button>Create</button>
    </form>
  </div>
</main>
{% endblock content %}

receipts/templates/receipts/newaccount.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <h1>Create Account</h1>
    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <button>Create</button>
    </form>
  </div>
</main>
{% endblock content %}

receipts/templates/receipts/newexpense.html
{% extends 'base.html' %} {% block content %}
<main>
  <div>
    <h1>Create Category</h1>
    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <button>Create</button>
    </form>
  </div>
</main>
{% endblock content %}